version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint --disable=E1101,C0103,R0903,R1705 $CODEBUILD_SRC_DIR/**/*.py
artifacts:
    files:
        - '**/*'