# Generated by Django 2.1.15 on 2024-03-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[('Bsc', 'Bsc'), ('Msc', 'Msc'), ('PGDiploma', 'PGDiploma')], default='Bsc', max_length=15)),
            ],
        ),
    ]
