# Generated by Django 4.2.11 on 2024-03-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='NewQuiz',
        ),
    ]
