# Generated by Django 2.1.15 on 2024-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0002_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('option_a', models.CharField(max_length=150)),
                ('option_b', models.CharField(max_length=150)),
                ('option_c', models.CharField(max_length=150)),
                ('option_d', models.CharField(max_length=150)),
                ('correct_answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
