# Generated by Django 4.2.11 on 2024-03-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0002_rename_quiz_newquiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewQuiz',
            new_name='Quiz',
        ),
    ]
