# Generated by Django 2.1.15 on 2024-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0003_auto_20240326_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct_answer',
        ),
    ]
