# Generated by Django 2.1.15 on 2024-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0004_auto_20240326_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
