# Generated by Django 4.2.11 on 2024-03-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizzDynamoApp', '0008_alter_quiz_id_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_address',
        ),
    ]
